// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: grpc/calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Op    string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Var   string                 `protobuf:"bytes,3,opt,name=var,proto3" json:"var,omitempty"`
	// Types that are valid to be assigned to Left:
	//
	//	*Instruction_LeftInt
	//	*Instruction_LeftVar
	Left isInstruction_Left `protobuf_oneof:"left"`
	// Types that are valid to be assigned to Right:
	//
	//	*Instruction_RightInt
	//	*Instruction_RightVar
	Right         isInstruction_Right `protobuf_oneof:"right"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_grpc_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_grpc_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Instruction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Instruction) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Instruction) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *Instruction) GetLeft() isInstruction_Left {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Instruction) GetLeftInt() int64 {
	if x != nil {
		if x, ok := x.Left.(*Instruction_LeftInt); ok {
			return x.LeftInt
		}
	}
	return 0
}

func (x *Instruction) GetLeftVar() string {
	if x != nil {
		if x, ok := x.Left.(*Instruction_LeftVar); ok {
			return x.LeftVar
		}
	}
	return ""
}

func (x *Instruction) GetRight() isInstruction_Right {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *Instruction) GetRightInt() int64 {
	if x != nil {
		if x, ok := x.Right.(*Instruction_RightInt); ok {
			return x.RightInt
		}
	}
	return 0
}

func (x *Instruction) GetRightVar() string {
	if x != nil {
		if x, ok := x.Right.(*Instruction_RightVar); ok {
			return x.RightVar
		}
	}
	return ""
}

type isInstruction_Left interface {
	isInstruction_Left()
}

type Instruction_LeftInt struct {
	LeftInt int64 `protobuf:"varint,4,opt,name=left_int,json=leftInt,proto3,oneof"`
}

type Instruction_LeftVar struct {
	LeftVar string `protobuf:"bytes,5,opt,name=left_var,json=leftVar,proto3,oneof"`
}

func (*Instruction_LeftInt) isInstruction_Left() {}

func (*Instruction_LeftVar) isInstruction_Left() {}

type isInstruction_Right interface {
	isInstruction_Right()
}

type Instruction_RightInt struct {
	RightInt int64 `protobuf:"varint,6,opt,name=right_int,json=rightInt,proto3,oneof"`
}

type Instruction_RightVar struct {
	RightVar string `protobuf:"bytes,7,opt,name=right_var,json=rightVar,proto3,oneof"`
}

func (*Instruction_RightInt) isInstruction_Right() {}

func (*Instruction_RightVar) isInstruction_Right() {}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Var           string                 `protobuf:"bytes,1,opt,name=var,proto3" json:"var,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_grpc_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_grpc_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *Result) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CalculationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instructions  []*Instruction         `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationRequest) Reset() {
	*x = CalculationRequest{}
	mi := &file_grpc_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRequest) ProtoMessage() {}

func (x *CalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRequest.ProtoReflect.Descriptor instead.
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return file_grpc_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *CalculationRequest) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type CalculationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Result              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationResponse) Reset() {
	*x = CalculationResponse{}
	mi := &file_grpc_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationResponse) ProtoMessage() {}

func (x *CalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationResponse.ProtoReflect.Descriptor instead.
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return file_grpc_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *CalculationResponse) GetItems() []*Result {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_grpc_calculator_proto protoreflect.FileDescriptor

const file_grpc_calculator_proto_rawDesc = "" +
	"\n" +
	"\x15grpc/calculator.proto\x12\n" +
	"calculator\"\xcc\x01\n" +
	"\vInstruction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x10\n" +
	"\x03var\x18\x03 \x01(\tR\x03var\x12\x1b\n" +
	"\bleft_int\x18\x04 \x01(\x03H\x00R\aleftInt\x12\x1b\n" +
	"\bleft_var\x18\x05 \x01(\tH\x00R\aleftVar\x12\x1d\n" +
	"\tright_int\x18\x06 \x01(\x03H\x01R\brightInt\x12\x1d\n" +
	"\tright_var\x18\a \x01(\tH\x01R\brightVarB\x06\n" +
	"\x04leftB\a\n" +
	"\x05right\"0\n" +
	"\x06Result\x12\x10\n" +
	"\x03var\x18\x01 \x01(\tR\x03var\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"Q\n" +
	"\x12CalculationRequest\x12;\n" +
	"\finstructions\x18\x01 \x03(\v2\x17.calculator.InstructionR\finstructions\"?\n" +
	"\x13CalculationResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.calculator.ResultR\x05items2a\n" +
	"\x11CalculatorService\x12L\n" +
	"\tCalculate\x12\x1e.calculator.CalculationRequest\x1a\x1f.calculator.CalculationResponseB\x0eZ\f.;calculatorb\x06proto3"

var (
	file_grpc_calculator_proto_rawDescOnce sync.Once
	file_grpc_calculator_proto_rawDescData []byte
)

func file_grpc_calculator_proto_rawDescGZIP() []byte {
	file_grpc_calculator_proto_rawDescOnce.Do(func() {
		file_grpc_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_calculator_proto_rawDesc), len(file_grpc_calculator_proto_rawDesc)))
	})
	return file_grpc_calculator_proto_rawDescData
}

var file_grpc_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_calculator_proto_goTypes = []any{
	(*Instruction)(nil),         // 0: calculator.Instruction
	(*Result)(nil),              // 1: calculator.Result
	(*CalculationRequest)(nil),  // 2: calculator.CalculationRequest
	(*CalculationResponse)(nil), // 3: calculator.CalculationResponse
}
var file_grpc_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.CalculationRequest.instructions:type_name -> calculator.Instruction
	1, // 1: calculator.CalculationResponse.items:type_name -> calculator.Result
	2, // 2: calculator.CalculatorService.Calculate:input_type -> calculator.CalculationRequest
	3, // 3: calculator.CalculatorService.Calculate:output_type -> calculator.CalculationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_calculator_proto_init() }
func file_grpc_calculator_proto_init() {
	if File_grpc_calculator_proto != nil {
		return
	}
	file_grpc_calculator_proto_msgTypes[0].OneofWrappers = []any{
		(*Instruction_LeftInt)(nil),
		(*Instruction_LeftVar)(nil),
		(*Instruction_RightInt)(nil),
		(*Instruction_RightVar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_calculator_proto_rawDesc), len(file_grpc_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_calculator_proto_goTypes,
		DependencyIndexes: file_grpc_calculator_proto_depIdxs,
		MessageInfos:      file_grpc_calculator_proto_msgTypes,
	}.Build()
	File_grpc_calculator_proto = out.File
	file_grpc_calculator_proto_goTypes = nil
	file_grpc_calculator_proto_depIdxs = nil
}
